### ISSUE TITLE
Use a release version of InfluxDB

### ISSUE THREAD

**Issue by hferentschik** [hferentschik/balena-weather#1]
Currently, the code depends on a specific SHA with an unclear origin.

```yaml
  influxdb:
    container_name: influxdb
    image: influxdb@sha256:73f876e0c3bd02900f829d4884f53fdfffd7098dd572406ba549eed955bf821f
    restart: always
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - 'influxdb-data:/data'
    ports:
      - "8086:8086"
```
